class ResumoJava3 {
    public static void main(String[] args) {
        System.out.println("Revisão completa da parte em Java:");
        System.out.println();
        System.out.println("1. Variáveis, tipos e sintaxe básica:");
        System.out.println("   - Java é fortemente tipada: int, double, boolean, String, char.");
        System.out.println("   - Declaração e atribuição:");
        System.out.println("       int idade = 20;");
        System.out.println("       double salario = 1250.75;");
        System.out.println("       boolean aprovado = true;");
        System.out.println("       String nome = \"Maria\";");
        System.out.println();
        System.out.println("2. Operadores e expressões:");
        System.out.println("   - Aritméticos: +, -, *, /, % para calcular valores.");
        System.out.println("   - Relacionais: ==, !=, >, <, >=, <= para comparar.");
        System.out.println("   - Lógicos: &&, ||, ! para combinar condições.");
        System.out.println();
        System.out.println("3. Condicionais e tomadas de decisão:");
        System.out.println("   - if/else para decidir fluxos:");
        System.out.println("       if (nota >= 7) {");
        System.out.println("           System.out.println(\"Aprovado\");");
        System.out.println("       } else {");
        System.out.println("           System.out.println(\"Reprovado\");");
        System.out.println("       }");
        System.out.println("   - switch/case para múltiplas opções:");
        System.out.println("       switch (opcao) {");
        System.out.println("           case 1: System.out.println(\"Soma\"); break;");
        System.out.println("           case 2: System.out.println(\"Subtração\"); break;");
        System.out.println("           default: System.out.println(\"Opção inválida\");");
        System.out.println("       }");
        System.out.println();
        System.out.println("4. Laços de repetição:");
        System.out.println("   - for: repetição com contagem conhecida:");
        System.out.println("       for (int i = 0; i < 5; i++) {");
        System.out.println("           System.out.println(i);");
        System.out.println("       }");
        System.out.println("   - while: repete enquanto a condição for verdadeira:");
        System.out.println("       int j = 0;");
        System.out.println("       while (j < 5) {");
        System.out.println("           j++;");
        System.out.println("       }");
        System.out.println("   - do/while: executa pelo menos uma vez:");
        System.out.println("       int k = 0;");
        System.out.println("       do {");
        System.out.println("           k++;");
        System.out.println("       } while (k < 5);");
        System.out.println();
        System.out.println("5. Modularização e métodos:");
        System.out.println("   - Métodos void para ações sem retorno:");
        System.out.println("       public static void mostrarMenu() {");
        System.out.println("           System.out.println(\"1. Soma\");");
        System.out.println("       }");
        System.out.println("   - Métodos com retorno para calcular resultados:");
        System.out.println("       public static int somar(int a, int b) {");
        System.out.println("           return a + b;");
        System.out.println("       }");
        System.out.println("   - Parâmetros e reutilização de código:");
        System.out.println("       int resultado = somar(3, 4);");
        System.out.println();
        System.out.println("6. Recursividade:");
        System.out.println("   - Função chama a si mesma para resolver problemas repetitivos.");
        System.out.println("   - Exemplo clássico: cálculo do fatorial:");
        System.out.println("       public static int fatorial(int n) {");
        System.out.println("           if (n <= 1) {");
        System.out.println("               return 1;");
        System.out.println("           }");
        System.out.println("           return n * fatorial(n - 1);");
        System.out.println("       }");
        System.out.println("   - Caso base é essencial para evitar loop infinito.");
        System.out.println();
        System.out.println("7. Vetores (arrays) e matrizes:");
        System.out.println("   - Arrays unidimensionais para listas simples:");
        System.out.println("       int[] notas = {5, 7, 9};");
        System.out.println("       for (int i = 0; i < notas.length; i++) {");
        System.out.println("           System.out.println(notas[i]);");
        System.out.println("       }");
        System.out.println("   - Matrizes bidimensionais para tabelas:");
        System.out.println("       int[][] matriz = new int[3][3];");
        System.out.println("       matriz[0][0] = 1;");
        System.out.println("   - Uso de loops aninhados para percorrer linhas e colunas.");
        System.out.println("   - Exemplos úteis: soma de todos os elementos, maior valor por linha.");
        System.out.println();
        System.out.println("8. Classe Arrays e manipulação de arrays:");
        System.out.println("   - Arrays.sort(array) para ordenar valores.");
        System.out.println("   - Arrays.copyOf(array, novoTamanho) para copiar ou redimensionar.");
        System.out.println("   - Arrays.binarySearch(array, valor) para busca em arrays ordenados.");
        System.out.println();
        System.out.println("9. Strings e manipulação de texto:");
        System.out.println("   - String é imutável em Java.");
        System.out.println("   - Métodos úteis: length(), substring(), indexOf(), replace(), split().");
        System.out.println("   - Extração de dados de logs exige leitura linha a linha e parsing.");
        System.out.println();
        System.out.println("10. Tópicos específicos e conceitos adicionais:");
        System.out.println("   - Operadores bit a bit: &, |, ^ para manipulação de bits.");
        System.out.println("   - ULA (Unidade Lógica e Aritmética): conceito importante em arquitetura.");
        System.out.println("   - Boas práticas: nomear variáveis com clareza, criar métodos pequenos.");
        System.out.println();
        System.out.println("11. Exemplo prático de revisão completa:");
        System.out.println("   - Ler uma nota, verificar condição, calcular média, armazenar em array.");
        System.out.println("   - Usar métodos para separar a leitura, o cálculo e a exibição.");
        System.out.println();
        System.out.println("12. O que você já domina:");
        System.out.println("   - Lógica sequencial, condicional e de repetição em Java.");
        System.out.println("   - Modularização com métodos void e métodos com retorno.");
        System.out.println("   - Estruturas de dados básicas: arrays e matrizes.");
        System.out.println();
        System.out.println("13. Próximo passo natural:");
        System.out.println("   - Programação Orientada a Objetos: classes, objetos, atributos, métodos.");
        System.out.println("   - Encapsulamento, construtores, herança e polimorfismo.");
        System.out.println();
        System.out.println("Conclusão:");
        System.out.println("   - Esta revisão cobre a parte em Java que você estudou até agora.");
        System.out.println("   - Se quiser, posso detalhar qualquer um destes tópicos com exemplos reais.");
    }
}
